var books = [
    {
        cgbID: 382,
        title: "Basic Carpet 01",
        file: "Basic_carpet_01",
        url: "basic-carpet-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Fabric",
        colors: [
            "gray",
            "white",
        ],
        method: "procedural",
        tags: [
            "carpet",
            "fabric",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 383,
        title: "Bathroom Floor Tiles 01",
        file: "Bathroom_floor_tiles_01",
        url: "bathroom-floor-tiles-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "white",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
            "floor",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 384,
        title: "Bathroom Floor Tiles 02",
        file: "Bathroom_floor_tiles_02",
        url: "bathroom-floor-tiles-02",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "gray",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
            "floor",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 385,
        title: "Bathroom Floor Tiles 03",
        file: "Bathroom_floor_tiles_03",
        url: "bathroom-floor-tiles-03",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "black",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
            "floor",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 386,
        title: "Bathroom Tiles 01",
        file: "Bathroom_tiles_01",
        url: "bathroom-tiles-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "black",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 387,
        title: "Bathroom Tiles 02",
        file: "Bathroom_tiles_02",
        url: "bathroom-tiles-02",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "gray",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 388,
        title: "Bathroom Tiles 03",
        file: "Bathroom_tiles_03",
        url: "bathroom-tiles-03",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "white",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 389,
        title: "Long Tiles 01",
        file: "Long_tiles_01",
        url: "long-tiles-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "blue",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 390,
        title: "Long Tiles 02",
        file: "Long_tiles_02",
        url: "long-tiles-02",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "white",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 391,
        title: "Long Tiles 03",
        file: "Long_tiles_03",
        url: "long-tiles-03",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "gray",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 392,
        title: "Long Tiles 04",
        file: "Long_tiles_04",
        url: "long-tiles-04",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "black",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    
    {
        cgbID: 393,
        title: "Parquet Flooring 06",
        file: "Parquet_flooring_06",
        url: "parquet-flooring-06",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Parquet",
        colors: [
            "brown",
        ],
        method: "procedural",
        tags: [
            "parquet",
            "flooring",
            "floor",
            "wood",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 394,
        title: "Parquet Flooring 07",
        file: "Parquet_flooring_07",
        url: "parquet-flooring-07",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Parquet",
        colors: [
            "brown",
        ],
        method: "procedural",
        tags: [
            "parquet",
            "flooring",
            "floor",
            "wood",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 395,
        title: "Parquet Flooring 08",
        file: "Parquet_flooring_08",
        url: "parquet-flooring-08",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Parquet",
        colors: [
            "brown",
        ],
        method: "procedural",
        tags: [
            "parquet",
            "flooring",
            "floor",
            "wood",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 396,
        title: "Parquet Flooring 09",
        file: "Parquet_flooring_09",
        url: "parquet-flooring-09",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Parquet",
        colors: [
            "brown",
        ],
        method: "procedural",
        tags: [
            "parquet",
            "flooring",
            "floor",
            "wood",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 397,
        title: "Parquet Flooring 10",
        file: "Parquet_flooring_10",
        url: "parquet-flooring-10",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Parquet",
        colors: [
            "brown",
        ],
        method: "procedural",
        tags: [
            "parquet",
            "flooring",
            "floor",
            "wood",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 398,
        title: "Quilt 01",
        file: "Quilt_01",
        url: "quilt-01",
        resolution: 4,
        files: ["AO", "Base_Color", "Height", "Normal", "Roughness"],
        category: "Fabric",
        colors: [
            "purple",
        ],
        method: "procedural",
        tags: [
            "pink",
            "quilt",
            "fabric",
            "seating",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 399,
        title: "Small Tiles 01",
        file: "Small_tiles_01",
        url: "small-tiles-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "black",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
            "small",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 400,
        title: "Small Tiles 02",
        file: "Small_tiles_02",
        url: "small-tiles-02",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "gray",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
            "small",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 401,
        title: "Small Tiles 03",
        file: "Small_tiles_03",
        url: "small-tiles-03",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "whie",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
            "small",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 402,
        title: "Small Tiles 04",
        file: "Small_tiles_04",
        url: "small-tiles-04",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "blue",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "bathroom",
            "small",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 403,
        title: "Stone Tiles Floor 01",
        file: "Stone_tiles_floor_01",
        url: "stone-tiles-floor-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "gray",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "stone",
            "plates",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 404,
        title: "Stone Tiles Floor 02",
        file: "Stone_tiles_floor_02",
        url: "stone-tiles-floor-02",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "gray",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "stone",
            "plates",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 405,
        title: "Stone Tiles Floor 03",
        file: "Stone_tiles_floor_03",
        url: "stone-tiles-floor-03",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Tiles",
        colors: [
            "white",
            "gray",
        ],
        method: "procedural",
        tags: [
            "tiles",
            "stone",
            "plates",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 406,
        title: "White Brick Wall 01",
        file: "White_brick_wall_01",
        url: "white-brick-wall-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Walls",
        colors: [
            "white",
        ],
        method: "procedural",
        tags: [
            "brick",
            "wall",
            "painted",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },
    {
        cgbID: 407,
        title: "Wooden Plates Floor 01",
        file: "Wooden_plates_floor_01",
        url: "wooden-plates-floor-01",
        resolution: 4,
        files: ["Base_Color", "Height", "Normal", "Roughness"],
        category: "Wood",
        colors: [
            "brown",
        ],
        method: "procedural",
        tags: [
            "wood",
            "wooden",
            "plates",
            "floor",
        ],
        type: "pbr",
        releasedate: "2019-11-07",
    },


];